class Lexicon:
    player_choice_label = "Wie viele Einheiten werden Sie produzieren (von 0 bis 70)?"
    comprehension_question_1 = "Wenn der Ihnen zugewiesene Teilnehmer 25 Einheiten produziert und Sie ebenfalls 25 Einheiten produzieren, wie hoch ist dann Ihre Vergütung gemäß Vertrag A?"
    comprehension_question_2 = "Angenommen, der Ihnen zugewiesene Teilnehmer produziert 24 Einheiten. Welche Menge führt unter Vertrag B zu der höchsten Vergütung?"
    comprehension_question_3 = "Angenommen, der Ihnen zugewiesene Teilnehmer produziert 33 Einheiten und Sie produzieren ebenfalls 33 Einheiten. Wie hoch wird Ihre Vergütung gemäß Vertrag A sein?"
    not_payoff_relevant = "Keine Auswirkungen auf die Vergütung"
    at_least_one_answer_wrong = "Mindestens eine der Antworten war inkorrekt."
    wait_page_text_waiting = "Warte auf die Entscheidung des anderen Teilnehmers."
    title_Introduction_General = "Einführung in das Experiment"
    title_Introduction_Market = "Informationen über das Marktumfeld"
    title_info_calculator = "Informationen über den Profit-Rechner"
    contract_a = "VERTRAG A"
    contract_b = "VERTRAG B"
