class Lexicon:
    player_choice_label = "How many units will you produce (from 0 to 70)?"
    comprehension_question_1 = "Suppose the participant you are matched with produces 25 units and you produce 25 units. What will be your compensation under the contract A?"
    comprehension_question_2 = "Suppose the participant you are matched with produces 24 units. What quantity will result in the highest compensation under the contract B?"
    comprehension_question_3 = "Suppose the participant you are matched with produces 33 units and you produce 33 units. What will be your compensation under the contract A?"
    not_payoff_relevant = "Not payoff relevant"
    at_least_one_answer_wrong = "At least one of the answers was incorrect."
    wait_page_text_waiting = "Waiting for the other participant to decide."
    title_Introduction_General = "Introduction to the Experiment"
    title_Introduction_Market = "Information about the market environment"
    title_info_calculator = "Information about the profit calculator"