class Lexicon:
    player_choice_label = "Wie viele Einheiten werden Sie produzieren (von 0 bis 70)?"
    comprehension_question_1 = "Wenn die andere Person eine Menge von 25 wählt und Sie ebenfalls eine Menge von 25 wählen, wie hoch ist dann Ihre Vergütung gemäß Vertrag A?"
    comprehension_question_2 = "Angenommen, die andere Person wählt eine Menge von 24. Welche Menge führt unter Vertrag B zu der höchsten Vergütung?"
    comprehension_question_3 = "Angenommen, die andere Person eine Menge von 33 wählt und Sie ebenfalls eine Menge von 33 wählen. Wie hoch wird Ihre Vergütung gemäß Vertrag A sein?"
    not_payoff_relevant = "Keine Auswirkungen auf die Vergütung"
    at_least_one_answer_wrong = "Mindestens eine der Antworten war inkorrekt."
    wait_page_text_waiting = "Warte auf die Entscheidung des anderen Teilnehmers."
    title_Introduction_General = "Einführung in das Experiment"
    title_Introduction_Market = "Informationen"
    title_info_calculator = "Informationen"
    contract_a = "VERTRAG A"
    contract_b = "VERTRAG B"
